apiVersion: v1
kind: ConfigMap
metadata:
  name: items-api-config
  namespace: default
data:
  APP_ENV: "production"
  SERVICE_NAME: "items-api"
  REDIS_URL: "redis://:$REDIS_PASSWORD@items-api-redis-master.items-api.svc.cluster.local:6379/0"
